### ISSUE TITLE
Bundler could not find compatible versions for gem "sidekiq"

### ISSUE THREAD

**Issue by funkenstrahlen** [cryo28/sidekiq_status#25]
```
Bundler could not find compatible versions for gem "sidekiq":
  In Gemfile:
    sidekiq_status (>= 0) ruby depends on
      sidekiq (~> 2.3.3) ruby

    sidekiq (2.17.7)
```

**Comment by Deekor** [comment]
Im getting:
```
Bundler could not find compatible versions for gem "sidekiq":
  In snapshot (Gemfile.lock):
    sidekiq (= 3.5.4)

  In Gemfile:
    sidekiq-limit_fetch (>= 0) ruby depends on
      sidekiq (< 4.0, >= 2.6.5) ruby

    sidekiq_status (>= 0) ruby depends on
      sidekiq (~> 2.3.3) ruby

    sidekiq (< 4, >= 3.3) ruby
```

even after `bundle update`. According to the line of code @cryo28 [referenced above](https://github.com/cryo28/sidekiq_status/blob/master/sidekiq_status.gemspec#L19) shouldn't it be happy with my current `sidekiq` version? Why is it looking for `~> 2.3.3`?

**Comment by Deekor** [comment]
I think the gem remote is off or something, I added 

```
gem 'sidekiq_status', '~> 1.0', git: 'https://github.com/cryo28/sidekiq_status.git'
```

and it installed just fine...

**Comment by cryo28** [comment]
@Deekor  I have not yet pushed 1.1.0 to rubygems. I want to give it a little time to bake in my production system. Please feel free to pull it from github in the meanwhile
