### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by ncuesta** [cryo28/sidekiq_status#45]
Hi, @cryo28. I see you've merged some PRs providing compat with Sidekiq 4+.

Could you please release a new version with the latest changes so we can use it directly from Rubygems?

Thanks for this awesome gem!

Cheers,

**Comment by cryo28** [comment]
Pushed 1.2.0 to rubygems...

**Comment by ncuesta** [comment]
Yay! Thanks!

--
Nahuel Cuesta Luengo
@ncuestal · nahuelcuestaluengo@gmail.com
