### ISSUE TITLE
How to clean the status records in Redis manually?

### ISSUE THREAD

**Issue by smoothdvd** [cryo28/sidekiq_status#49]

**Comment by cryo28** [comment]
See [SidekiqStatus::Container.delete](/cryo28/sidekiq_status/blob/master/lib/sidekiq_status/container.rb#L63)

**Comment by smoothdvd** [comment]
@cryo28 Thanks

**Comment by waruboy** [comment]
@cryo28 Ah I needed this too. Thanks! Might be better if this is in Readme?
